### ISSUE TITLE
Safecheck slot marker ID

### ISSUE THREAD

**Issue by Aiden-32** [ThoughtOverflow/CouncilGame#14]
https://github.com/ThoughtOverflow/CouncilGame/blob/baeae7d568c4c25c30e56e1e1ac9c9f4078095ac/Source/CouncilGame/Private/Gameplay/UMG/InventoryWrapper.cpp#L80

Make sure slot marker ID isn't set to -1, it causes an infinite loop.

**Comment by bence056** [comment]
Fixed - 526f8b0dcc5915c4ad2142c76f91c5eecbdabeda
